#!/bin/bash
for i in $(seq 1 2 99)
do
    echo $i    
done

/* initialize i as loop variable, for i in a sequence of numbers generated by command seq from 1 to 99 with a step increment of 2,
 * beginning of loop variable
 * print the current value of i as standard output 
 * end of loop variable */
